export const CHANGE_CURRENTLY_MENU = 'CHANGE_CURRENTLY_MENU';
export const CHANGE_HOME_PAGE = 'CHANGE_HOME_PAGE';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_PERSONAL_INFO = 'SAVE_PERSONAL_INFO';
